/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#006c49",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#ffc278",
        "on-primary-container": "#bcceff",
        "on-primary-fixed-variant": "#00419c",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c6d5",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "tertiary-container": "#7c4d00",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "surface": "#f8f9ff",
        "primary": "#003c90",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#4edea3",
        "primary-container": "#0f52ba",
        "secondary-container": "#6cf8bb",
        "primary-fixed-dim": "#b0c6ff",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#1d59c1",
        "inverse-primary": "#b0c6ff",
        "background": "#f8f9ff",
        "on-secondary-fixed": "#002113",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed": "#001945",
        "error": "#ba1a1a",
        "on-surface-variant": "#434653",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#ffddb8",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        "tertiary": "#5c3800",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "primary-fixed": "#d9e2ff",
        "outline": "#737784",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "sm": "8px",
        "container-max": "1280px",
        "md": "16px",
        "xl": "48px",
        "lg": "24px",
        "gutter": "20px",
        "base": "4px",
        "xs": "4px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
